// Generated by gencpp from file hmcl_msgs/MissionWaypoint.msg
// DO NOT EDIT!


#ifndef HMCL_MSGS_MESSAGE_MISSIONWAYPOINT_H
#define HMCL_MSGS_MESSAGE_MISSIONWAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace hmcl_msgs
{
template <class ContainerAllocator>
struct MissionWaypoint_
{
  typedef MissionWaypoint_<ContainerAllocator> Type;

  MissionWaypoint_()
    : start()
    , end()
    , remain(0)  {
    }
  MissionWaypoint_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , end(_alloc)
    , remain(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _end_type;
  _end_type end;

   typedef int32_t _remain_type;
  _remain_type remain;





  typedef boost::shared_ptr< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> const> ConstPtr;

}; // struct MissionWaypoint_

typedef ::hmcl_msgs::MissionWaypoint_<std::allocator<void> > MissionWaypoint;

typedef boost::shared_ptr< ::hmcl_msgs::MissionWaypoint > MissionWaypointPtr;
typedef boost::shared_ptr< ::hmcl_msgs::MissionWaypoint const> MissionWaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator1> & lhs, const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.end == rhs.end &&
    lhs.remain == rhs.remain;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator1> & lhs, const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hmcl_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "787e74dd4a3e0df7f1ef38d7abe84225";
  }

  static const char* value(const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x787e74dd4a3e0df7ULL;
  static const uint64_t static_value2 = 0xf1ef38d7abe84225ULL;
};

template<class ContainerAllocator>
struct DataType< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hmcl_msgs/MissionWaypoint";
  }

  static const char* value(const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# global id\n"
"geometry_msgs/Point start\n"
"geometry_msgs/Point end\n"
"int32 remain\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.end);
      stream.next(m.remain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MissionWaypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hmcl_msgs::MissionWaypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hmcl_msgs::MissionWaypoint_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.end);
    s << indent << "remain: ";
    Printer<int32_t>::stream(s, indent + "  ", v.remain);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HMCL_MSGS_MESSAGE_MISSIONWAYPOINT_H
