# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mobileye_msgs/TSRVisionOnlySign.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TSRVisionOnlySign(genpy.Message):
  _md5sum = "81ad54807425b67a5be6ad808e97e8ee"
  _type = "mobileye_msgs/TSRVisionOnlySign"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 vision_only_sign_type_display_1
uint8 vision_only_sign_type_display_2
uint8 vision_only_sign_type_display_3
uint8 vision_only_sign_type_display_4

uint8 supplementary_sign_type_display_1
uint8 supplementary_sign_type_display_2
uint8 supplementary_sign_type_display_3
uint8 supplementary_sign_type_display_4"""
  __slots__ = ['vision_only_sign_type_display_1','vision_only_sign_type_display_2','vision_only_sign_type_display_3','vision_only_sign_type_display_4','supplementary_sign_type_display_1','supplementary_sign_type_display_2','supplementary_sign_type_display_3','supplementary_sign_type_display_4']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vision_only_sign_type_display_1,vision_only_sign_type_display_2,vision_only_sign_type_display_3,vision_only_sign_type_display_4,supplementary_sign_type_display_1,supplementary_sign_type_display_2,supplementary_sign_type_display_3,supplementary_sign_type_display_4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TSRVisionOnlySign, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vision_only_sign_type_display_1 is None:
        self.vision_only_sign_type_display_1 = 0
      if self.vision_only_sign_type_display_2 is None:
        self.vision_only_sign_type_display_2 = 0
      if self.vision_only_sign_type_display_3 is None:
        self.vision_only_sign_type_display_3 = 0
      if self.vision_only_sign_type_display_4 is None:
        self.vision_only_sign_type_display_4 = 0
      if self.supplementary_sign_type_display_1 is None:
        self.supplementary_sign_type_display_1 = 0
      if self.supplementary_sign_type_display_2 is None:
        self.supplementary_sign_type_display_2 = 0
      if self.supplementary_sign_type_display_3 is None:
        self.supplementary_sign_type_display_3 = 0
      if self.supplementary_sign_type_display_4 is None:
        self.supplementary_sign_type_display_4 = 0
    else:
      self.vision_only_sign_type_display_1 = 0
      self.vision_only_sign_type_display_2 = 0
      self.vision_only_sign_type_display_3 = 0
      self.vision_only_sign_type_display_4 = 0
      self.supplementary_sign_type_display_1 = 0
      self.supplementary_sign_type_display_2 = 0
      self.supplementary_sign_type_display_3 = 0
      self.supplementary_sign_type_display_4 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.vision_only_sign_type_display_1, _x.vision_only_sign_type_display_2, _x.vision_only_sign_type_display_3, _x.vision_only_sign_type_display_4, _x.supplementary_sign_type_display_1, _x.supplementary_sign_type_display_2, _x.supplementary_sign_type_display_3, _x.supplementary_sign_type_display_4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.vision_only_sign_type_display_1, _x.vision_only_sign_type_display_2, _x.vision_only_sign_type_display_3, _x.vision_only_sign_type_display_4, _x.supplementary_sign_type_display_1, _x.supplementary_sign_type_display_2, _x.supplementary_sign_type_display_3, _x.supplementary_sign_type_display_4,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.vision_only_sign_type_display_1, _x.vision_only_sign_type_display_2, _x.vision_only_sign_type_display_3, _x.vision_only_sign_type_display_4, _x.supplementary_sign_type_display_1, _x.supplementary_sign_type_display_2, _x.supplementary_sign_type_display_3, _x.supplementary_sign_type_display_4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.vision_only_sign_type_display_1, _x.vision_only_sign_type_display_2, _x.vision_only_sign_type_display_3, _x.vision_only_sign_type_display_4, _x.supplementary_sign_type_display_1, _x.supplementary_sign_type_display_2, _x.supplementary_sign_type_display_3, _x.supplementary_sign_type_display_4,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
