# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hmcl_msgs/VehicleSCC.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class VehicleSCC(genpy.Message):
  _md5sum = "2b27ed567b1b24fdf57d28dea9993802"
  _type = "hmcl_msgs/VehicleSCC"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# sccmode -> off       = 0
# sccmode -> ready       = 1
# sccmode -> on       = 2
uint8 scc_mode
# scc takeover -> off       = 0
# scc takeover -> n      = 1
uint8 scc_takeover
float64 acceleration"""
  __slots__ = ['scc_mode','scc_takeover','acceleration']
  _slot_types = ['uint8','uint8','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       scc_mode,scc_takeover,acceleration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleSCC, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.scc_mode is None:
        self.scc_mode = 0
      if self.scc_takeover is None:
        self.scc_takeover = 0
      if self.acceleration is None:
        self.acceleration = 0.
    else:
      self.scc_mode = 0
      self.scc_takeover = 0
      self.acceleration = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd().pack(_x.scc_mode, _x.scc_takeover, _x.acceleration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.scc_mode, _x.scc_takeover, _x.acceleration,) = _get_struct_2Bd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Bd().pack(_x.scc_mode, _x.scc_takeover, _x.acceleration))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.scc_mode, _x.scc_takeover, _x.acceleration,) = _get_struct_2Bd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Bd = None
def _get_struct_2Bd():
    global _struct_2Bd
    if _struct_2Bd is None:
        _struct_2Bd = struct.Struct("<2Bd")
    return _struct_2Bd
