(cl:in-package autorally_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AVERAGETIMEBETWEENPOSES-VAL
          AVERAGETIMEBETWEENPOSES
          AVERAGEOPTIMIZATIONCYCLETIME-VAL
          AVERAGEOPTIMIZATIONCYCLETIME
          AVERAGESLEEPTIME-VAL
          AVERAGESLEEPTIME
))