(cl:in-package autorally_msgs-msg)
(cl:export '(HZ-VAL
          HZ
          NUM_TIMESTEPS-VAL
          NUM_TIMESTEPS
          NUM_ITERS-VAL
          NUM_ITERS
          GAMMA-VAL
          GAMMA
          INIT_STEERING-VAL
          INIT_STEERING
          INIT_THROTTLE-VAL
          INIT_THROTTLE
          STEERING_VAR-VAL
          STEERING_VAR
          THROTTLE_VAR-VAL
          THROTTLE_VAR
          MAX_THROTTLE-VAL
          MAX_THROTTLE
          SPEED_COEFFICIENT-VAL
          SPEED_COEFFICIENT
          TRACK_COEFFICIENT-VAL
          TRACK_COEFFICIENT
          MAX_SLIP_ANGLE-VAL
          MAX_SLIP_ANGLE
          TRACK_SLOP-VAL
          TRACK_SLOP
          CRASH_COEFF-VAL
          CRASH_COEFF
          MAP_PATH-VAL
          MAP_PATH
          DESIRED_SPEED-VAL
          DESIRED_SPEED
))