(cl:in-package autorally_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          THROTTLERELAYENABLED-VAL
          THROTTLERELAYENABLED
          AUTONOMOUSENABLED-VAL
          AUTONOMOUSENABLED
          RUNSTOPMOTIONENABLED-VAL
          RUNSTOPMOTIONENABLED
          STEERINGCOMMANDER-VAL
          STEERINGCOMMANDER
          STEERING-VAL
          STEERING
          THROTTLECOMMANDER-VAL
          THROTTLECOMMANDER
          THROTTLE-VAL
          THROTTLE
          FRONTBRAKECOMMANDER-VAL
          FRONTBRAKECOMMANDER
          FRONTBRAKE-VAL
          FRONTBRAKE
))