// Generated by gencpp from file microstrain_inertial_msgs/GetAccelNoise.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETACCELNOISE_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETACCELNOISE_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/GetAccelNoiseRequest.h>
#include <microstrain_inertial_msgs/GetAccelNoiseResponse.h>


namespace microstrain_inertial_msgs
{

struct GetAccelNoise
{

typedef GetAccelNoiseRequest Request;
typedef GetAccelNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAccelNoise
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetAccelNoise > {
  static const char* value()
  {
    return "f98ca1a5e4f9d504cd0b08eeeda072c5";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetAccelNoise&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::GetAccelNoise > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/GetAccelNoise";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetAccelNoise&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelNoiseRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelNoise >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetAccelNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::GetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelNoiseRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelNoise >
template<>
struct DataType< ::microstrain_inertial_msgs::GetAccelNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::GetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelNoiseResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelNoise >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetAccelNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::GetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelNoiseResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelNoise >
template<>
struct DataType< ::microstrain_inertial_msgs::GetAccelNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::GetAccelNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETACCELNOISE_H
