// Generated by gencpp from file microstrain_inertial_msgs/GetAccelBiasModel.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETACCELBIASMODEL_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETACCELBIASMODEL_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/GetAccelBiasModelRequest.h>
#include <microstrain_inertial_msgs/GetAccelBiasModelResponse.h>


namespace microstrain_inertial_msgs
{

struct GetAccelBiasModel
{

typedef GetAccelBiasModelRequest Request;
typedef GetAccelBiasModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAccelBiasModel
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModel > {
  static const char* value()
  {
    return "b507c17fd666c16c0721d62595a47085";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetAccelBiasModel&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::GetAccelBiasModel > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/GetAccelBiasModel";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetAccelBiasModel&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModelRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModel >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelBiasModelRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelBiasModel >
template<>
struct DataType< ::microstrain_inertial_msgs::GetAccelBiasModelRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::GetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModelResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModel >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::GetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelBiasModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelBiasModelResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::GetAccelBiasModel >
template<>
struct DataType< ::microstrain_inertial_msgs::GetAccelBiasModelResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::GetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetAccelBiasModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETACCELBIASMODEL_H
