// Generated by gencpp from file microstrain_inertial_msgs/GetDynamicsMode.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETDYNAMICSMODE_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETDYNAMICSMODE_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/GetDynamicsModeRequest.h>
#include <microstrain_inertial_msgs/GetDynamicsModeResponse.h>


namespace microstrain_inertial_msgs
{

struct GetDynamicsMode
{

typedef GetDynamicsModeRequest Request;
typedef GetDynamicsModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDynamicsMode
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetDynamicsMode > {
  static const char* value()
  {
    return "4315dfa070d15c7ffc8d87836f8ad09c";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetDynamicsMode&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::GetDynamicsMode > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/GetDynamicsMode";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetDynamicsMode&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetDynamicsModeRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetDynamicsMode >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetDynamicsModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::GetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetDynamicsModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::GetDynamicsModeRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::GetDynamicsMode >
template<>
struct DataType< ::microstrain_inertial_msgs::GetDynamicsModeRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::GetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetDynamicsModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetDynamicsModeResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::GetDynamicsMode >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::GetDynamicsModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::GetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetDynamicsModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::GetDynamicsModeResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::GetDynamicsMode >
template<>
struct DataType< ::microstrain_inertial_msgs::GetDynamicsModeResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::GetDynamicsMode >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::GetDynamicsModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETDYNAMICSMODE_H
