// Generated by gencpp from file microstrain_inertial_msgs/GetHeadingSourceResponse.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETHEADINGSOURCERESPONSE_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETHEADINGSOURCERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct GetHeadingSourceResponse_
{
  typedef GetHeadingSourceResponse_<ContainerAllocator> Type;

  GetHeadingSourceResponse_()
    : heading_source(0)
    , success(false)  {
    }
  GetHeadingSourceResponse_(const ContainerAllocator& _alloc)
    : heading_source(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int8_t _heading_source_type;
  _heading_source_type heading_source;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHeadingSourceResponse_

typedef ::microstrain_inertial_msgs::GetHeadingSourceResponse_<std::allocator<void> > GetHeadingSourceResponse;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::GetHeadingSourceResponse > GetHeadingSourceResponsePtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::GetHeadingSourceResponse const> GetHeadingSourceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.heading_source == rhs.heading_source &&
    lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f4a68a47587634cd4d34560ad178beb";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f4a68a47587634cULL;
  static const uint64_t static_value2 = 0xd4d34560ad178bebULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/GetHeadingSourceResponse";
  }

  static const char* value(const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 heading_source\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading_source);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHeadingSourceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::GetHeadingSourceResponse_<ContainerAllocator>& v)
  {
    s << indent << "heading_source: ";
    Printer<int8_t>::stream(s, indent + "  ", v.heading_source);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_GETHEADINGSOURCERESPONSE_H
