// Generated by gencpp from file microstrain_inertial_msgs/InitFilterEuler.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_INITFILTEREULER_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_INITFILTEREULER_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/InitFilterEulerRequest.h>
#include <microstrain_inertial_msgs/InitFilterEulerResponse.h>


namespace microstrain_inertial_msgs
{

struct InitFilterEuler
{

typedef InitFilterEulerRequest Request;
typedef InitFilterEulerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitFilterEuler
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::InitFilterEuler > {
  static const char* value()
  {
    return "dae0af6e9e855f125599090c94e6955e";
  }

  static const char* value(const ::microstrain_inertial_msgs::InitFilterEuler&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::InitFilterEuler > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/InitFilterEuler";
  }

  static const char* value(const ::microstrain_inertial_msgs::InitFilterEuler&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::InitFilterEulerRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::InitFilterEuler >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::InitFilterEulerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::InitFilterEuler >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::InitFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::InitFilterEulerRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::InitFilterEuler >
template<>
struct DataType< ::microstrain_inertial_msgs::InitFilterEulerRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::InitFilterEuler >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::InitFilterEulerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::InitFilterEulerResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::InitFilterEuler >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::InitFilterEulerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::InitFilterEuler >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::InitFilterEulerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::InitFilterEulerResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::InitFilterEuler >
template<>
struct DataType< ::microstrain_inertial_msgs::InitFilterEulerResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::InitFilterEuler >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::InitFilterEulerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_INITFILTEREULER_H
