// Generated by gencpp from file microstrain_inertial_msgs/SetAccelBiasModel.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETACCELBIASMODEL_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETACCELBIASMODEL_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/SetAccelBiasModelRequest.h>
#include <microstrain_inertial_msgs/SetAccelBiasModelResponse.h>


namespace microstrain_inertial_msgs
{

struct SetAccelBiasModel
{

typedef SetAccelBiasModelRequest Request;
typedef SetAccelBiasModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAccelBiasModel
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModel > {
  static const char* value()
  {
    return "f3cdd18c97add875be98974ab1d992b9";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetAccelBiasModel&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::SetAccelBiasModel > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/SetAccelBiasModel";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetAccelBiasModel&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModelRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModel >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetAccelBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetAccelBiasModelRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetAccelBiasModel >
template<>
struct DataType< ::microstrain_inertial_msgs::SetAccelBiasModelRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetAccelBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModelResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModel >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetAccelBiasModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetAccelBiasModelResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetAccelBiasModel >
template<>
struct DataType< ::microstrain_inertial_msgs::SetAccelBiasModelResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetAccelBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetAccelBiasModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETACCELBIASMODEL_H
