// Generated by gencpp from file microstrain_inertial_msgs/SetFilterSpeedLeverArm.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETFILTERSPEEDLEVERARM_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETFILTERSPEEDLEVERARM_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/SetFilterSpeedLeverArmRequest.h>
#include <microstrain_inertial_msgs/SetFilterSpeedLeverArmResponse.h>


namespace microstrain_inertial_msgs
{

struct SetFilterSpeedLeverArm
{

typedef SetFilterSpeedLeverArmRequest Request;
typedef SetFilterSpeedLeverArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFilterSpeedLeverArm
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm > {
  static const char* value()
  {
    return "17d27ff1259ce523baf9de57b7c37e18";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetFilterSpeedLeverArm&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/SetFilterSpeedLeverArm";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetFilterSpeedLeverArm&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetFilterSpeedLeverArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >
template<>
struct DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetFilterSpeedLeverArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetFilterSpeedLeverArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >
template<>
struct DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArmResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetFilterSpeedLeverArm >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetFilterSpeedLeverArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETFILTERSPEEDLEVERARM_H
