// Generated by gencpp from file microstrain_inertial_msgs/SetGyroBiasModel.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETGYROBIASMODEL_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETGYROBIASMODEL_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/SetGyroBiasModelRequest.h>
#include <microstrain_inertial_msgs/SetGyroBiasModelResponse.h>


namespace microstrain_inertial_msgs
{

struct SetGyroBiasModel
{

typedef SetGyroBiasModelRequest Request;
typedef SetGyroBiasModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroBiasModel
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModel > {
  static const char* value()
  {
    return "f3cdd18c97add875be98974ab1d992b9";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetGyroBiasModel&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::SetGyroBiasModel > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/SetGyroBiasModel";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetGyroBiasModel&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModelRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModel >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroBiasModelRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroBiasModel >
template<>
struct DataType< ::microstrain_inertial_msgs::SetGyroBiasModelRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroBiasModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModelResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModel >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroBiasModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroBiasModelResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroBiasModel >
template<>
struct DataType< ::microstrain_inertial_msgs::SetGyroBiasModelResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetGyroBiasModel >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroBiasModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETGYROBIASMODEL_H
