// Generated by gencpp from file microstrain_inertial_msgs/SetGyroNoise.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETGYRONOISE_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETGYRONOISE_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/SetGyroNoiseRequest.h>
#include <microstrain_inertial_msgs/SetGyroNoiseResponse.h>


namespace microstrain_inertial_msgs
{

struct SetGyroNoise
{

typedef SetGyroNoiseRequest Request;
typedef SetGyroNoiseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGyroNoise
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetGyroNoise > {
  static const char* value()
  {
    return "6a73c0e939ba0cee17d40a2e3a5f667f";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetGyroNoise&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::SetGyroNoise > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/SetGyroNoise";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetGyroNoise&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroNoiseRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroNoise >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetGyroNoiseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroNoiseRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroNoise >
template<>
struct DataType< ::microstrain_inertial_msgs::SetGyroNoiseRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroNoiseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroNoiseResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetGyroNoise >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetGyroNoiseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroNoiseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroNoiseResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetGyroNoise >
template<>
struct DataType< ::microstrain_inertial_msgs::SetGyroNoiseResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetGyroNoise >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetGyroNoiseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETGYRONOISE_H
