// Generated by gencpp from file microstrain_inertial_msgs/SetHeadingSourceRequest.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETHEADINGSOURCEREQUEST_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETHEADINGSOURCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace microstrain_inertial_msgs
{
template <class ContainerAllocator>
struct SetHeadingSourceRequest_
{
  typedef SetHeadingSourceRequest_<ContainerAllocator> Type;

  SetHeadingSourceRequest_()
    : heading_source(0)  {
    }
  SetHeadingSourceRequest_(const ContainerAllocator& _alloc)
    : heading_source(0)  {
  (void)_alloc;
    }



   typedef int8_t _heading_source_type;
  _heading_source_type heading_source;





  typedef boost::shared_ptr< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHeadingSourceRequest_

typedef ::microstrain_inertial_msgs::SetHeadingSourceRequest_<std::allocator<void> > SetHeadingSourceRequest;

typedef boost::shared_ptr< ::microstrain_inertial_msgs::SetHeadingSourceRequest > SetHeadingSourceRequestPtr;
typedef boost::shared_ptr< ::microstrain_inertial_msgs::SetHeadingSourceRequest const> SetHeadingSourceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.heading_source == rhs.heading_source;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator1> & lhs, const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace microstrain_inertial_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c645f74f48e2efd41041018e43ce0ff2";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc645f74f48e2efd4ULL;
  static const uint64_t static_value2 = 0x1041018e43ce0ff2ULL;
};

template<class ContainerAllocator>
struct DataType< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "microstrain_inertial_msgs/SetHeadingSourceRequest";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 heading_source\n"
;
  }

  static const char* value(const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading_source);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHeadingSourceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::microstrain_inertial_msgs::SetHeadingSourceRequest_<ContainerAllocator>& v)
  {
    s << indent << "heading_source: ";
    Printer<int8_t>::stream(s, indent + "  ", v.heading_source);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETHEADINGSOURCEREQUEST_H
