// Generated by gencpp from file microstrain_inertial_msgs/SetSensor2VehicleRotation.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETSENSOR2VEHICLEROTATION_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETSENSOR2VEHICLEROTATION_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/SetSensor2VehicleRotationRequest.h>
#include <microstrain_inertial_msgs/SetSensor2VehicleRotationResponse.h>


namespace microstrain_inertial_msgs
{

struct SetSensor2VehicleRotation
{

typedef SetSensor2VehicleRotationRequest Request;
typedef SetSensor2VehicleRotationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensor2VehicleRotation
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotation > {
  static const char* value()
  {
    return "dae0af6e9e855f125599090c94e6955e";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleRotation&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotation > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/SetSensor2VehicleRotation";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleRotation&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotationRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleRotationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotationRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >
template<>
struct DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotationRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleRotationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotationResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleRotationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotationResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >
template<>
struct DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotationResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetSensor2VehicleRotation >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleRotationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETSENSOR2VEHICLEROTATION_H
