// Generated by gencpp from file microstrain_inertial_msgs/SetSensor2VehicleOffset.msg
// DO NOT EDIT!


#ifndef MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETSENSOR2VEHICLEOFFSET_H
#define MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETSENSOR2VEHICLEOFFSET_H

#include <ros/service_traits.h>


#include <microstrain_inertial_msgs/SetSensor2VehicleOffsetRequest.h>
#include <microstrain_inertial_msgs/SetSensor2VehicleOffsetResponse.h>


namespace microstrain_inertial_msgs
{

struct SetSensor2VehicleOffset
{

typedef SetSensor2VehicleOffsetRequest Request;
typedef SetSensor2VehicleOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSensor2VehicleOffset
} // namespace microstrain_inertial_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffset > {
  static const char* value()
  {
    return "17d27ff1259ce523baf9de57b7c37e18";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleOffset&) { return value(); }
};

template<>
struct DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffset > {
  static const char* value()
  {
    return "microstrain_inertial_msgs/SetSensor2VehicleOffset";
  }

  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleOffset&) { return value(); }
};


// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetRequest> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetRequest> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >
template<>
struct DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetResponse> should match
// service_traits::MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >
template<>
struct MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetResponse> should match
// service_traits::DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >
template<>
struct DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::microstrain_inertial_msgs::SetSensor2VehicleOffset >::value();
  }
  static const char* value(const ::microstrain_inertial_msgs::SetSensor2VehicleOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MICROSTRAIN_INERTIAL_MSGS_MESSAGE_SETSENSOR2VEHICLEOFFSET_H
