// Generated by gencpp from file mobileye_msgs/MobileyeInfo_lane.msg
// DO NOT EDIT!


#ifndef MOBILEYE_MSGS_MESSAGE_MOBILEYEINFO_LANE_H
#define MOBILEYE_MSGS_MESSAGE_MOBILEYEINFO_LANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mobileye_msgs/Lane.h>

namespace mobileye_msgs
{
template <class ContainerAllocator>
struct MobileyeInfo_lane_
{
  typedef MobileyeInfo_lane_<ContainerAllocator> Type;

  MobileyeInfo_lane_()
    : header()
    , lane()  {
    }
  MobileyeInfo_lane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lane(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mobileye_msgs::Lane_<ContainerAllocator>  _lane_type;
  _lane_type lane;





  typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> const> ConstPtr;

}; // struct MobileyeInfo_lane_

typedef ::mobileye_msgs::MobileyeInfo_lane_<std::allocator<void> > MobileyeInfo_lane;

typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_lane > MobileyeInfo_lanePtr;
typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_lane const> MobileyeInfo_laneConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator1> & lhs, const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lane == rhs.lane;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator1> & lhs, const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobileye_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2167664513fbefa299d496bdde8fbd05";
  }

  static const char* value(const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2167664513fbefa2ULL;
  static const uint64_t static_value2 = 0x99d496bdde8fbd05ULL;
};

template<class ContainerAllocator>
struct DataType< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobileye_msgs/MobileyeInfo_lane";
  }

  static const char* value(const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"Lane lane\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mobileye_msgs/Lane\n"
"float32 lane_curvature\n"
"float32 lane_heading\n"
"\n"
"bool ca\n"
"float32 pitch_angle\n"
"float32 yaw_angle\n"
"\n"
"bool right_ldw_availability\n"
"bool left_ldw_availability\n"
;
  }

  static const char* value(const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lane);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MobileyeInfo_lane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobileye_msgs::MobileyeInfo_lane_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lane: ";
    s << std::endl;
    Printer< ::mobileye_msgs::Lane_<ContainerAllocator> >::stream(s, indent + "  ", v.lane);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILEYE_MSGS_MESSAGE_MOBILEYEINFO_LANE_H
