// Generated by gencpp from file mobileye_msgs/MobileyeInfo_seeq.msg
// DO NOT EDIT!


#ifndef MOBILEYE_MSGS_MESSAGE_MOBILEYEINFO_SEEQ_H
#define MOBILEYE_MSGS_MESSAGE_MOBILEYEINFO_SEEQ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mobileye_msgs/SeeQ.h>

namespace mobileye_msgs
{
template <class ContainerAllocator>
struct MobileyeInfo_seeq_
{
  typedef MobileyeInfo_seeq_<ContainerAllocator> Type;

  MobileyeInfo_seeq_()
    : header()
    , seeq()  {
    }
  MobileyeInfo_seeq_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , seeq(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::mobileye_msgs::SeeQ_<ContainerAllocator>  _seeq_type;
  _seeq_type seeq;





  typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> const> ConstPtr;

}; // struct MobileyeInfo_seeq_

typedef ::mobileye_msgs::MobileyeInfo_seeq_<std::allocator<void> > MobileyeInfo_seeq;

typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_seeq > MobileyeInfo_seeqPtr;
typedef boost::shared_ptr< ::mobileye_msgs::MobileyeInfo_seeq const> MobileyeInfo_seeqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator1> & lhs, const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.seeq == rhs.seeq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator1> & lhs, const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mobileye_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44adbcbb0282c17f8d689edcb40bf0ce";
  }

  static const char* value(const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44adbcbb0282c17fULL;
  static const uint64_t static_value2 = 0x8d689edcb40bf0ceULL;
};

template<class ContainerAllocator>
struct DataType< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mobileye_msgs/MobileyeInfo_seeq";
  }

  static const char* value(const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"SeeQ seeq\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mobileye_msgs/SeeQ\n"
"uint32 serial_number\n"
"uint64 production_date\n"
"\n"
"uint8 brain_version_major\n"
"uint8 brain_version_minor\n"
"uint8 mest_version_major\n"
"uint8 mest_version_minor\n"
"uint8 mest_version_subminor\n"
"uint8 mest_version_patch_number\n"
;
  }

  static const char* value(const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.seeq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MobileyeInfo_seeq_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mobileye_msgs::MobileyeInfo_seeq_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "seeq: ";
    s << std::endl;
    Printer< ::mobileye_msgs::SeeQ_<ContainerAllocator> >::stream(s, indent + "  ", v.seeq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOBILEYE_MSGS_MESSAGE_MOBILEYEINFO_SEEQ_H
