(cl:in-package mobileye_msgs-msg)
(cl:export '(SOUND_TYPE-VAL
          SOUND_TYPE
          PEDS_IN_DZ-VAL
          PEDS_IN_DZ
          PEDS_FCW-VAL
          PEDS_FCW
          TIME_INDICATOR-VAL
          TIME_INDICATOR
          ERROR_VALID-VAL
          ERROR_VALID
          ERROR_CODE-VAL
          ERROR_CODE
          ZERO_SPEED-VAL
          ZERO_SPEED
          HEADWAY_VALID-VAL
          HEADWAY_VALID
          HEADWAY_MEASUREMENT-VAL
          HEADWAY_MEASUREMENT
          LDW_OFF-VAL
          LDW_OFF
          LEFT_LDW_ON-VAL
          LEFT_LDW_ON
          RIGHT_LDW_ON-VAL
          RIGHT_LDW_ON
          FCW_ON-VAL
          FCW_ON
          MAINTENANCE-VAL
          MAINTENANCE
          FAILSAFE-VAL
          FAILSAFE
          TSR_ENABLED-VAL
          TSR_ENABLED
          HW_REPEATABLE_ENABLED-VAL
          HW_REPEATABLE_ENABLED
          HEADWAY_WARNING_LEVEL-VAL
          HEADWAY_WARNING_LEVEL
          TSR_WARNING_LEVEL-VAL
          TSR_WARNING_LEVEL
          TAMPER_ALERT-VAL
          TAMPER_ALERT
))