(cl:in-package mobileye_msgs-msg)
(cl:export '(SERIAL_NUMBER-VAL
          SERIAL_NUMBER
          PRODUCTION_DATE-VAL
          PRODUCTION_DATE
          BRAIN_VERSION_MAJOR-VAL
          BRAIN_VERSION_MAJOR
          BRAIN_VERSION_MINOR-VAL
          BRAIN_VERSION_MINOR
          MEST_VERSION_MAJOR-VAL
          MEST_VERSION_MAJOR
          MEST_VERSION_MINOR-VAL
          MEST_VERSION_MINOR
          MEST_VERSION_SUBMINOR-VAL
          MEST_VERSION_SUBMINOR
          MEST_VERSION_PATCH_NUMBER-VAL
          MEST_VERSION_PATCH_NUMBER
))