(cl:in-package mobileye_msgs-msg)
(cl:export '(LANE_TYPE-VAL
          LANE_TYPE
          QUALITY-VAL
          QUALITY
          MODEL_DEGREE-VAL
          MODEL_DEGREE
          POSITION_PARAMETER_C0-VAL
          POSITION_PARAMETER_C0
          CURVATURE_PARAMETER_C2-VAL
          CURVATURE_PARAMETER_C2
          CURVATURE_DERIVATIVE_C3-VAL
          CURVATURE_DERIVATIVE_C3
          WIDTH_MARKING-VAL
          WIDTH_MARKING
          HEADING_ANGLE_PARAMETER_C1-VAL
          HEADING_ANGLE_PARAMETER_C1
          VIEW_RANGE-VAL
          VIEW_RANGE
          VIEW_RANGE_AVAILABILITY-VAL
          VIEW_RANGE_AVAILABILITY
))