
classdef RecognizeLightStateRequest < ros.Message
    %RecognizeLightStateRequest MATLAB implementation of hmcl_msgs/RecognizeLightStateRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'hmcl_msgs/RecognizeLightStateRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '4abd893b134895139a9fa041573de884' % The MD5 Checksum of the message definition
        PropertyList = { 'RoiImage' } % List of non-constant message properties
        ROSPropertyList = { 'roi_image' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.sensor_msgs.Image' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        RoiImage
    end
    methods
        function set.RoiImage(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.sensor_msgs.Image'};
            validateattributes(val, validClasses, validAttributes, 'RecognizeLightStateRequest', 'RoiImage')
            obj.RoiImage = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.hmcl_msgs.RecognizeLightStateRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.hmcl_msgs.RecognizeLightStateRequest;
            obj.reload(strObj);
        end
    end
end
